export { default as BrandSection } from "./BrandSection"
export { default as Hero } from "./Hero"
export { default as TestimonialSection } from "./TestimonialSection"
export { default as WhatWeDoSection } from "./WhatWeDoSection"
export { default as WorkSection } from "./WorkSection"
