import { NavBar } from "@/components/NavBar"
import { SubFooter } from "@/components/SubFooter"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "../styles/globals.scss"

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  style: "normal",
  weight: ["100", "300", "400", "500"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(poppins.variable, "Background ")}>
        <NavBar />
        <main className="px-[30px]">{children}</main>
        <SubFooter />
      </body>
    </html>
  )
}
